### ISSUE TITLE
FC on Swift Black

### ISSUE THREAD

**Issue by jereksel** [jereksel/LibreSubstratum#153]
Fatal Exception: java.lang.IllegalArgumentException: background can not be translucent: #4dffffff
       at android.support.v4.graphics.ColorUtils.calculateMinimumAlpha(ColorUtils.java:121)
       at android.support.v7.graphics.Palette$Swatch.ensureTextColorsGenerated(Palette.java:525)
       at android.support.v7.graphics.Palette$Swatch.getTitleTextColor(Palette.java:508)
       at com.jereksel.libresubstratum.adapters.Type1SpinnerArrayAdapter.getDropDownView(Type1SpinnerArrayAdapter.kt:68)
       at android.widget.Spinner$DropDownAdapter.getDropDownView(Spinner.java:975)
       at android.widget.Spinner$DropDownAdapter.getView(Spinner.java:971)
       at android.widget.Spinner.measureContentWidth(Spinner.java:845)
       at android.widget.Spinner$DropdownPopup.computeContentWidth(Spinner.java:1206)
       at android.widget.Spinner$DropdownPopup.show(Spinner.java:1232)
       at android.widget.Spinner.performClick(Spinner.java:770)
       at android.support.v7.widget.AppCompatSpinner.performClick(AppCompatSpinner.java:448)
       at android.view.View$PerformClick.run(View.java:22453)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)

**Comment by jereksel** [comment]
```
Fatal Exception: java.lang.IllegalArgumentException: background can not be translucent: #4dffffff
       at android.support.v4.graphics.ColorUtils.calculateMinimumAlpha(ColorUtils.java:121)
       at android.support.v7.graphics.Palette$Swatch.ensureTextColorsGenerated(Palette.java:525)
       at android.support.v7.graphics.Palette$Swatch.getTitleTextColor(Palette.java:508)
       at com.jereksel.libresubstratum.adapters.Type1SpinnerArrayAdapter.getDropDownView(Type1SpinnerArrayAdapter.kt:69)
       at android.widget.Spinner$DropDownAdapter.getDropDownView(Spinner.java:975)
       at android.widget.Spinner$DropDownAdapter.getView(Spinner.java:971)
       at android.widget.Spinner.measureContentWidth(Spinner.java:845)
       at android.widget.Spinner$DropdownPopup.computeContentWidth(Spinner.java:1206)
       at android.widget.Spinner$DropdownPopup.show(Spinner.java:1232)
       at android.widget.Spinner.performClick(Spinner.java:770)
       at android.support.v7.widget.AppCompatSpinner.performClick(AppCompatSpinner.java:448)
       at android.view.View$PerformClick.run(View.java:22433)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6236)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```
